apiVersion: v1
kind: Service
metadata:
  name: devops-deploy
  labels:
    app: custom
spec:
  type: NodePort 
  selector:
    app: custom
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
